### ISSUE TITLE
Enhancement: Possibility to add multiple calendars

### ISSUE THREAD

**Issue by DarkFox** [000miix/DailyGrapher#2]
I have multiple calendars that I'd like to add (Work, personal, TripIt, etc.). Would it be possible to do that?

**Comment by 000miix** [comment]
This just has been merged, created by @trstns!

you  can now add calendar entities as a list

**Comment by DarkFox** [comment]
Looks like it didn't work.
If I use a list in entity, it doesn't render, and if I use the new entitites parameter, I get the error "You need to define an entity"

The standard way of having multiple entities, is to have `entity` accept either a single entity as a string, or a list of strings, then detect which it is in the backend.

**Comment by trstns** [comment]
I'm not sure why it isn't working for you.  From the error message it sounds like it is still using the older version, so maybe your cache needs to be cleared.

You're right that I should have used the entity and have it work for both cases.  I have made the change on my install and will submit a new pull request soon.

**Comment by DarkFox** [comment]
You are right. A ctrl+shift+r full reload fixed it. I guess the reload resources button isn't quite enough.

**Comment by trstns** [comment]
Just following up, the new update which uses only the entity parameter has been merged.  Hopefully this works for you.

**Comment by DarkFox** [comment]
It works great, thanks! :)
