### ISSUE TITLE
Support 24hour time format

### ISSUE THREAD

**Issue by GrumpyMeow** [000miix/DailyGrapher#3]
I just saw a Reddit-post about this component. I'm wanted to try it out for myself and my kids.
Just a minor thing i noticed is that the time is displayed using AM/PM. I'm used to the 24-hour time format.
Also i would expect the graph to have a range of 24hours.. 

Hopefully i'll get around to extend your graph and provide a PR.

**Comment by fett1979** [comment]
same here

**Comment by GrumpyMeow** [comment]
I see that this issue is partially resolved. Thanks!
("display_24_hour_time")
